import hashlib
from datetime import datetime

import streamlit as st

from pdf_utils import extract_pdf_pages
from rag_core import (
    build_chunks,
    build_index,
    retrieve_chunks,
    build_evidence_text,
    build_answer_prompt,
    build_repair_prompt,
    valid_citation_labels,
    looks_incomplete,
    force_basic_citations,
    format_evidence_cards,
)
from llm_client import generate_answer, get_secret


st.set_page_config(
    page_title="Healthcare RAG Lite",
    page_icon="🩺",
    layout="wide",
)


CUSTOM_CSS = """
<style>
.block-container {
    max-width: 1180px;
    padding-top: 2rem;
}

[data-testid="stSidebar"] {
    border-right: 1px solid rgba(148, 163, 184, 0.25);
}

.rag-card {
    border: 1px solid rgba(56, 189, 248, 0.35);
    background: rgba(15, 23, 42, 0.7);
    border-radius: 16px;
    padding: 18px;
    margin-bottom: 16px;
}

.small-muted {
    color: #94a3b8;
    font-size: 0.9rem;
}

.warning-card {
    border: 1px solid rgba(245, 158, 11, 0.5);
    background: rgba(120, 53, 15, 0.25);
    border-radius: 12px;
    padding: 12px;
}

.success-dot {
    height: 10px;
    width: 10px;
    background-color: #22c55e;
    border-radius: 50%;
    display: inline-block;
    margin-right: 8px;
}

.fail-dot {
    height: 10px;
    width: 10px;
    background-color: #ef4444;
    border-radius: 50%;
    display: inline-block;
    margin-right: 8px;
}
</style>
"""

st.markdown(CUSTOM_CSS, unsafe_allow_html=True)


def file_hash(file_bytes: bytes) -> str:
    return hashlib.sha256(file_bytes).hexdigest()


@st.cache_data(show_spinner=False)
def process_uploaded_files(file_payloads):
    all_pages = []

    for item in file_payloads:
        pages = extract_pdf_pages(item["bytes"], item["name"])
        all_pages.extend(pages)

    chunks = build_chunks(all_pages)

    if not chunks:
        return {
            "pages": all_pages,
            "chunks": [],
            "vectorizer": None,
            "matrix": None,
        }

    vectorizer, matrix = build_index(chunks)

    return {
        "pages": all_pages,
        "chunks": chunks,
        "vectorizer": vectorizer,
        "matrix": matrix,
    }


def init_state():
    if "messages" not in st.session_state:
        st.session_state.messages = []

    if "processed_key" not in st.session_state:
        st.session_state.processed_key = None

    if "rag_data" not in st.session_state:
        st.session_state.rag_data = None


def render_sidebar():
    st.sidebar.title("Healthcare RAG Lite")

    gemini_ready = bool(get_secret("GEMINI_API_KEY"))
    groq_ready = bool(get_secret("GROQ_API_KEY"))

    if gemini_ready:
        st.sidebar.markdown('<span class="success-dot"></span>Gemini API ready', unsafe_allow_html=True)
    else:
        st.sidebar.markdown('<span class="fail-dot"></span>Gemini API missing', unsafe_allow_html=True)

    if groq_ready:
        st.sidebar.markdown('<span class="success-dot"></span>Groq fallback ready', unsafe_allow_html=True)
    else:
        st.sidebar.markdown('<span class="fail-dot"></span>Groq fallback missing', unsafe_allow_html=True)

    st.sidebar.divider()

    if st.sidebar.button("New chat", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

    if st.sidebar.button("Clear processed PDFs", use_container_width=True):
        st.session_state.processed_key = None
        st.session_state.rag_data = None
        st.session_state.messages = []
        st.rerun()

    st.sidebar.divider()

    st.sidebar.caption(
        "Lite version for public deployment. "
        "PDFs are processed in the current session. "
        "No permanent local database is used."
    )

    st.sidebar.caption("Educational use only. Not a diagnostic or prescribing system.")


def render_messages():
    for message in st.session_state.messages:
        role = message["role"]

        if role == "user":
            with st.chat_message("user", avatar="🧑"):
                st.markdown(message["content"])

        else:
            with st.chat_message("assistant", avatar="🩺"):
                st.markdown(message["content"])

                provider = message.get("provider")
                model = message.get("model")

                if provider and model:
                    st.caption(f"Generated by {provider} · {model}")

                evidence_cards = message.get("evidence_cards", [])
                if evidence_cards:
                    with st.expander(f"Evidence citations ({len(evidence_cards)})"):
                        for card in evidence_cards:
                            st.markdown(
                                f"**[{card['label']}] {card['source']} — page {card['page']}**"
                            )
                            st.write(card["text"])
                            st.divider()

                if message.get("citation_warning"):
                    st.warning(
                        "The answer was generated, but inline evidence labels needed automatic repair. "
                        "Review the evidence cards before relying on this answer."
                    )


def answer_question(question: str, answer_mode: str):
    rag_data = st.session_state.rag_data

    if not rag_data or not rag_data["chunks"]:
        st.error("Please upload and process at least one PDF first.")
        return

    retrieved = retrieve_chunks(
        question=question,
        chunks=rag_data["chunks"],
        vectorizer=rag_data["vectorizer"],
        matrix=rag_data["matrix"],
        top_k=8,
    )

    evidence_text = build_evidence_text(retrieved)
    allowed_labels = [chunk.label for chunk in retrieved]

    prompt = build_answer_prompt(
        question=question,
        evidence_text=evidence_text,
        answer_mode=answer_mode,
    )

    with st.spinner("Thinking with evidence..."):
        answer, provider, model = generate_answer(prompt, max_tokens=1800)

        citation_warning = False
        valid_labels = valid_citation_labels(answer, allowed_labels)

        if looks_incomplete(answer) or not valid_labels:
            repair_prompt = build_repair_prompt(
                question=question,
                draft_answer=answer,
                evidence_text=evidence_text,
            )

            try:
                repaired_answer, repair_provider, repair_model = generate_answer(
                    repair_prompt,
                    max_tokens=1600,
                )

                repaired_valid_labels = valid_citation_labels(
                    repaired_answer,
                    allowed_labels,
                )

                if repaired_valid_labels and not looks_incomplete(repaired_answer):
                    answer = repaired_answer
                    provider = repair_provider
                    model = repair_model
                else:
                    answer = force_basic_citations(answer, allowed_labels)
                    citation_warning = True

            except Exception:
                answer = force_basic_citations(answer, allowed_labels)
                citation_warning = True

        evidence_cards = format_evidence_cards(retrieved)

    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": answer,
            "provider": provider,
            "model": model,
            "evidence_cards": evidence_cards,
            "citation_warning": citation_warning,
        }
    )


def build_markdown_download() -> str:
    lines = []
    lines.append("# Healthcare RAG Lite Chat")
    lines.append("")
    lines.append(f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    for message in st.session_state.messages:
        if message["role"] == "user":
            lines.append("## User")
            lines.append(message["content"])
            lines.append("")
        else:
            lines.append("## Assistant")
            lines.append(message["content"])
            lines.append("")

            evidence_cards = message.get("evidence_cards", [])
            if evidence_cards:
                lines.append("### Evidence")
                for card in evidence_cards:
                    lines.append(f"- [{card['label']}] {card['source']}, page {card['page']}")
                lines.append("")

    return "\n".join(lines)


def main():
    init_state()
    render_sidebar()

    st.title("Healthcare Guidelines RAG Lite")
    st.caption(
        "Public Streamlit Cloud version: upload healthcare guideline PDFs, ask questions, "
        "and get evidence-grounded answers with citations."
    )

    uploaded_files = st.file_uploader(
        "Upload PDF guideline documents",
        type=["pdf"],
        accept_multiple_files=True,
    )

    col1, col2 = st.columns([1, 2])

    with col1:
        process_clicked = st.button("Process PDFs", type="primary", use_container_width=True)

    with col2:
        answer_mode = st.radio(
            "Answer mode",
            ["Smart Auto", "Deep Research", "Fast"],
            horizontal=True,
        )

    if uploaded_files and process_clicked:
        file_payloads = []

        for uploaded_file in uploaded_files:
            data = uploaded_file.getvalue()
            file_payloads.append(
                {
                    "name": uploaded_file.name,
                    "bytes": data,
                    "hash": file_hash(data),
                }
            )

        combined_key = "|".join(item["hash"] for item in file_payloads)

        with st.spinner("Processing PDFs and building retrieval index..."):
            rag_data = process_uploaded_files(file_payloads)

        st.session_state.processed_key = combined_key
        st.session_state.rag_data = rag_data
        st.session_state.messages = []

        page_count = len(rag_data["pages"])
        chunk_count = len(rag_data["chunks"])

        st.success(f"Processed {len(uploaded_files)} PDF(s), {page_count} page(s), {chunk_count} chunks.")

    if st.session_state.rag_data:
        pages = len(st.session_state.rag_data["pages"])
        chunks = len(st.session_state.rag_data["chunks"])
        st.info(f"Active knowledge base: {pages} page(s), {chunks} evidence chunk(s).")

    st.divider()

    render_messages()

    question = st.chat_input("Ask a question about the uploaded PDFs...")

    if question:
        st.session_state.messages.append(
            {
                "role": "user",
                "content": question,
            }
        )

        answer_question(question, answer_mode)
        st.rerun()

    if st.session_state.messages:
        markdown_text = build_markdown_download()

        st.download_button(
            "Download this chat as Markdown",
            data=markdown_text,
            file_name="healthcare_rag_lite_chat.md",
            mime="text/markdown",
        )


if __name__ == "__main__":
    main()